version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: pokelog-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./backend/.env
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    container_name: pokelog-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./frontend/.env
    command: npm run start